version: 2
updates:
 
  - package-ecosystem: "github-actions"
    target-branch: "main"
    directories: 
      - "/build-action"
      - "/hatch-conda"
      - "/hatch-lint"
      - "/permission_check"
      - "/setup-hatch"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 10
